import { describe,expect,it } from "vitest";
import { createGame, drawEvent, isGameOver, nextMonth, prepareMonth, processMonth, scoreGame, selectEventResponse, toggleAction } from "./game";
import type { GameEvent, GameState } from "../types";
import { EVENTS } from "../config";
describe("game engine",()=>{
 it("processes a month and preserves accounting equation",()=>{let s=prepareMonth(createGame("beginner",42));s=toggleAction(s,"ads");const n=processMonth(s);expect(n.history).toHaveLength(1);expect(n.financial.balance.cash).toBe(n.history[0].openingCash+n.financial.cashFlow.cashChange)});
 it("detects game over state",()=>{const s=createGame("advanced",1);expect(isGameOver({...s,gameOverReason:"test"})).toBe(true)});
 it("calculates bounded score",()=>{const score=scoreGame(createGame("beginner",1));expect(score.score).toBeGreaterThanOrEqual(0);expect(["S","A","B","C","D"]).toContain(score.rank)});
 it("same seed produces same event sequence",()=>{const a=createGame("advanced",1234),b=createGame("advanced",1234);expect(drawEvent(a)).toEqual(drawEvent(b))});
 it("records an event response and its learning impact",()=>{const event:GameEvent={id:"test",title:"test",description:"test",probability:1,duration:1,effect:{},lesson:"test",responses:[{id:"protect",label:"protect",description:"protect",cashCost:100,effect:{creditChange:2},learning:"cash lesson"}]};let s:GameState={...createGame("beginner",1),currentEvent:event};s=selectEventResponse(s,"protect");expect(s.selectedEventResponseId).toBe("protect");const result=processMonth(s);expect(result.history[0].eventResponse?.label).toBe("protect");expect(result.history[0].eventImpact).toContain("対応費用 0万円");expect(result.history[0].lesson).toContain("cash lesson")});
 it("offers at least two responses for every event",()=>{for(const event of EVENTS){expect(event.responses?.length,event.id).toBeGreaterThanOrEqual(2);for(const response of event.responses??[])expect(response.learning.length).toBeGreaterThan(0)}});
 it("can complete all 36 months with deterministic accounting",()=>{let s=createGame("advanced",98765);s={...s,financial:{...s.financial,balance:{...s.financial.balance,cash:1_000_000_000,equity:s.financial.balance.equity+998_000_000}}};for(let month=1;month<=36;month++){s=prepareMonth(s);if(s.currentEvent?.responses?.length)s=selectEventResponse(s,s.currentEvent.responses[0].id);s=toggleAction(s,"cost-cut");s=processMonth(s);if(month<36)s=nextMonth(s)}expect(s.history).toHaveLength(36);expect(s.screen).toBe("final");for(const result of s.history)expect(result.balance.cash).toBe(result.openingCash+result.cashFlow.cashChange)});
});
